version: "3"

services:
  backup:
    build: .
    environment:
      - BACKUP_SCHEDULE=1 0 0 * *
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASS=secret
      - DB_NAME=*
      - FTP_PROTO=ftp
      - FTP_HOST=192.168.144.1
      - FTP_USER=backup
      - FTP_PASS=Backup1234!
      - REMOTE_PATH=/Local_storage/Backup/Testing
    volumes:
      - ./:/app
      - ./etc/crontab:/etc/crontab
      - ./tmp/mysql:/data/mysql
    links:
      - ftp
      - mysql

  mysql:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=demo
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - ./tmp/mysql:/var/lib/mysql
      - ./tests/fixtures:/docker-entrypoint-initdb.d/

  ftp:
    image: delfer/alpine-ftp-server
    environment:
      - USERS=user|1234
    ports:
      - '20-21:20-21/tcp'
      - '40000-40009:40000-40009/tcp'
    volumes:
      - ./tmp/ftp:/ftp/user

  adminer:
    image: javanile/adminer
    environment:
      - MYSQL_DATABASE=demo
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 8080:8080
