version: "3"

services:
  backup:
    build: .
    command:
      - "* * * * * backup.sh"
    environment:
      - DB_NAME=demo
      - FTP_HOST=ftp
      - FTP_USER=user
      - FTP_PASS=123
      - REMOTE_PATH=/home/user/backup
    volumes:
      - ./:/app
      - ./crontab:/etc/crontab
      - ./tmp/mysql:/data/mysql
    links:
      - ftp
      - mysql

  mysql:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=demo
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - ./tmp/mysql:/var/lib/mysql

  ftp:
    image: garethflowers/ftp-server
    environment:
      - FTP_USER=user
      - FTP_PASS=123
    ports:
      - '20-21:20-21/tcp'
      - '40000-40009:40000-40009/tcp'
    volumes:
      - ./tmp/ftp:/home/user
